# For any catalog item, consider those in same directory as related files:
related_files_v2:
  - file: description.adoc
    load_into: /__meta__/catalog/description
    content_key: content
    set:
      format: asciidoc