---
#include notcatalogitem.yaml
cloudformation_retries: 0
clientvm_instance_type: t2.medium

purpose: development

foodict:
  bar: ok

##########################
# Babylon meta variables #
##########################

__meta__:

  # Catalog Item (OpenShift template)
  catalog:
    # OpenShift template where agnosticv-operator will
    # create the template
    namespace: openshift

    description: >-
      this is an OCP Clientvm

    tags:
      - babylon
      - ocp

  deployer:
    scm_url: https://github.com/redhat-cop/agnosticd.git
    scm_type: git
    scm_ref: development
    type: agnosticd
